[workspace]
resolver = "2"
members = [
    "crates/min-syntax",
    "crates/min-diagnostics",
]

[workspace.dependencies]
# Utilities
thiserror = "1.0"
tracing = "0.1"

# Testing
expect-test = "1.4"
insta = { version = "1.34", features = ["yaml"] }
