[package]
name = "min-syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
min-diagnostics = { path = "../min-diagnostics" }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
insta = { workspace = true }
